main:
    github_account: datadlog
    base_branch: dev
    feature_branch: feature_001_replace_text
    replace_text: { "example1": "example2", "sample1": "sample2" }
    file_pattern: "*.json" # For all the files replace ""
    github_access_token: <<provide access token>>
